version: '3.0'

services:
  nginx-nursery:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - static-nursery:/srv/static:rw
      - media-nursery:/srv/media:rw
    container_name: nginx-nursery
    restart: always
    depends_on:
      - uwsgi-nursery
    ports:
      - 80:80
      - 443:443

  uwsgi-nursery:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: /srv/project/src/docker/uwsgi/run-dev.sh
    volumes:
      - static-nursery:/srv/project/static
      - media-nursery:/srv/project/media
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
      - DISABLE_COLLECTSTATIC=1
      - PUDB_RDB_HOST=0.0.0.0
      - PUDB_RDB_PORT=6900
    ports:
      - 6900:6900
    restart: always
    container_name: uwsgi-nursery
    depends_on:
      - db-nursery

  db-nursery:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    restart: always
    container_name: db-nursery


volumes:
  media-nursery: {}
  static-nursery: {}
