# Generated by Django 2.0.1 on 2018-06-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Привели'), (2, 'Забрали')], default=1, verbose_name='Событие')),
                ('date', models.DateField(verbose_name='Дата')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Child', verbose_name='Ребенок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
    ]
